// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHost(arg1:main.SSHHost):Promise<void>;

export function ConnectSSH(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function GetAllTags():Promise<Array<string>>;

export function GetHosts():Promise<Array<main.SSHHost>>;

export function GetServerSettings(arg1:string):Promise<main.ServerSettings>;

export function GetSettings():Promise<main.AppSettings>;

export function ImportFromSSHConfig():Promise<number>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveServerSettings(arg1:string,arg2:main.ServerSettings):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function UpdateHost(arg1:main.SSHHost):Promise<void>;
