// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function ImportFromSSHConfig() {
  return window['go']['main']['App']['ImportFromSSHConfig']();
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function UpdateHost(arg1) {
  return window['go']['main']['App']['UpdateHost'](arg1);
}
